--Kiểm tra xem database đã tồn tại hay chưa, tồn tại thì xóa
IF EXISTS (SELECT * FROM sys.databases WHERE name = N'Nhom2')
BEGIN
    -- Đóng tất cả các kết nối đến cơ sở dữ liệu
    EXECUTE sp_MSforeachdb 'IF ''?'' = ''Nhom2'' 
    BEGIN 
        DECLARE @sql AS NVARCHAR(MAX) = ''USE [?]; ALTER DATABASE [?] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;''
        EXEC (@sql)
    END'
    -- Xóa tất cả các kết nối tới cơ sở dữ liệu (thực hiện qua hệ thống master)
    USE master;

    -- Xóa cơ sở dữ liệu nếu tồn tại
    DROP DATABASE [Nhom2];
END

-- Tạo cơ sở dữ liệu mới
CREATE DATABASE [Nhom2];
GO

-- Sử dụng cơ sở dữ liệu vừa tạo
USE [Nhom2];
GO

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG
(
    MAKHACHHANG CHAR(9) PRIMARY KEY,
    TENCONGTY NVARCHAR(50) not null,
    TENGIAODICH NVARCHAR(50) not null ,
    EMAIL VARCHAR(50) UNIQUE,
    DIENTHOAI VARCHAR(11) UNIQUE,
    FAX VARCHAR(20)
);

-- Tạo bảng QuocGia
CREATE TABLE QuocGia
(
    maQG CHAR(10) PRIMARY KEY,
    tenQG NVARCHAR(100) not null
);

-- Tạo bảng TinhTP
CREATE TABLE TinhTP
(
    maTP CHAR(10) PRIMARY KEY,
    tenTP NVARCHAR(100) not null ,
    maQG CHAR(10),
    CONSTRAINT fk_TinhTP_QuocGia FOREIGN KEY (maQG) REFERENCES QuocGia(maQG)
);

-- Tạo bảng QuanHuyen
CREATE TABLE QuanHuyen
(
    maQH CHAR(10) PRIMARY KEY,
    tenQH NVARCHAR(100) not null ,
    maTP CHAR(10),
    CONSTRAINT fk_QuanHuyen_TinhTP FOREIGN KEY (maTP) REFERENCES TinhTP(maTP)
);

-- Tạo bảng PhuongXa
CREATE TABLE PhuongXa
(
    maPX CHAR(10) PRIMARY KEY,
    tenPX NVARCHAR(100),
    maQH CHAR(10),
    CONSTRAINT fk_PhuongXa_QuanHuyen FOREIGN KEY (maQH) REFERENCES QuanHuyen(maQH)
);

-- Thêm cột maPX và soNhaTenDuong vào bảng KHACHHANG
ALTER TABLE KHACHHANG
    ADD maPX CHAR(10),
        soNhaTenDuong NVARCHAR(50) not null ;

-- Thêm ràng buộc khóa ngoại cho maPX trong bảng KHACHHANG
ALTER TABLE KHACHHANG
    ADD CONSTRAINT fk_KhachHang_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN
(
    MANHANVIEN CHAR(9) PRIMARY KEY,
    HO NVARCHAR(10),
    TEN NVARCHAR(30),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(50),
    DIENTHOAI VARCHAR(11) UNIQUE,
	EMAIL VARCHAR(50),
	FAX CHAR(50),
    LUONGCOBAN MONEY,
    PHUCAP MONEY,
    CONSTRAINT CK_NHANVIEN_NGAYSINH CHECK (DATEDIFF(YEAR, NGAYSINH, GETDATE()) BETWEEN 18 AND 60)
);
--xóa cột địa chỉ
ALTER TABLE NHANVIEN
	DROP COLUMN DIACHI
-- Thêm cột maPX và soNhaTenDuong vào bảng NHANVIEN
ALTER TABLE NHANVIEN
    ADD maPX CHAR(10),
        soNhaTenDuong NVARCHAR(50) not null;

-- Thêm ràng buộc khóa ngoại cho maPX trong bảng NHANVIEN
ALTER TABLE NHANVIEN
    ADD CONSTRAINT fk_NhanVien_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX);
-- Sửa số điện thoại 10 chữ số hoặc 11 chữ số duy nhất trong NhanVien
alter table NHANVIEN
	add constraint chk_NhanVien_SDT check (
    DIENTHOAI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
    OR DIENTHOAI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') ;
alter table NHANVIEN
	add constraint uq_NhanVien_SDT unique (DIENTHOAI);
--   bổ sung email có ký tự @ bắt đầu bằng chữ cái   trong bảng NHANVIEN
alter table NHANVIEN
	add constraint chk_KhachHang_Email check (EMAIL LIKE '[a-zA-Z]%@%');

-- Tạo bảng DONDATHANG
CREATE TABLE DONDATHANG
(
    SOHOADON CHAR(9) PRIMARY KEY,
    MAKHACHHANG CHAR(9),
    MANHANVIEN CHAR(9),
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(50) not null ,
    CONSTRAINT fk_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    CONSTRAINT fk_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT chk_DONDATHANG_NGAYGIAOHANG CHECK (NGAYGIAOHANG >= NGAYDATHANG),
    CONSTRAINT chk_DONDATHANG_NGAYCHUYENHANG CHECK (NGAYCHUYENHANG >= NGAYDATHANG)
);

-- ngày tạo đơn hàng bằng ngày hiện tại
alter table  DONDATHANG 
	add constraint  df_DonDatHang_ngayDatHang default  getdate() for NGAYDATHANG;

-- Sửa số điện thoại 10 chữ số hoặc 11 chữ số duy nhất trong KhachHang
alter table KHACHHANG
	add constraint chk_KhachHang_SDT check (
	DIENTHOAI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
    OR DIENTHOAI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'  ) ;
alter table KHACHHANG
	add constraint uq_KhachHang_SDT unique (DIENTHOAI);
--   bổ sung email có ký tự @ bắt đầu bằng chữ cái   trong bảng KhachHang
alter table KHACHHANG
	add constraint chk_Kh_Email check (EMAIL LIKE '[a-zA-Z]%@%');

-- Tạo bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP
(
    MACONGTY CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(50) not null ,
    DIACHI NVARCHAR(50),
    DIENTHOAI VARCHAR(11) UNIQUE,
    FAX VARCHAR(20),
    EMAIL NVARCHAR(50) UNIQUE
);
-- Sửa số điện thoại 10 chữ số hoặc 11 chữ số duy nhất trong NHACUNGCAP
alter table NHACUNGCAP
	add constraint chk_NhaCungCap_SDT check (
	DIENTHOAI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
    OR DIENTHOAI like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'  ) ;
--   bổ sung email có ký tự @ bắt đầu bằng chữ cái   trong bảng NHACUNGCAP
alter table NHACUNGCAP
	add constraint chk_NhaCungCap_Email check (EMAIL LIKE '[a-zA-Z]%@%');
--xóa cột địa chỉ
ALTER TABLE NHACUNGCAP
	DROP COLUMN DIACHI
-- Thêm cột maPX và soNhaTenDuong vào bảng NHACUNGCAP
ALTER TABLE NHACUNGCAP
    ADD maPX CHAR(10),
        soNhaTenDuong NVARCHAR(50) not null;

-- Thêm ràng buộc khóa ngoại cho maPX trong bảng NHACUNGCAP
ALTER TABLE NHACUNGCAP
    ADD CONSTRAINT fk_NhaCungCap_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX)
	;

-- Tạo bảng LOAIHANG
CREATE TABLE LOAIHANG
(
    MALOAIHANG CHAR(5) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(50)
);

-- Tạo bảng MATHANG
CREATE TABLE MATHANG
(
    MAHANG CHAR(5) PRIMARY KEY,
    TENHANG NVARCHAR(50),
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(5),
    SOLUONG INT CHECK (SOLUONG >= 0),
    DONVITINH NVARCHAR(5),
    GIAHANG MONEY CHECK (GIAHANG >= 0),
    CONSTRAINT fk_MATHANG_NHACUNGCAP FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    CONSTRAINT fk_MATHANG_LOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);


-- Tạo bảng CHITIETDATHANG
CREATE TABLE CHITIETDATHANG
(
    SOHOADON CHAR(9),
    MAHANG CHAR(5),
    GIABAN MONEY CHECK (GIABAN >= 0),
    SOLUONG INT DEFAULT 1 CHECK (SOLUONG > 0),
    MUCGIAMGIA MONEY DEFAULT 0,
    PRIMARY KEY (SOHOADON, MAHANG),
    CONSTRAINT fk_CHITIETDATHANG_DONDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
    CONSTRAINT fk_CHITIETDATHANG_MATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
);



-- thêm on update và delete cascade
-- Xóa các ràng buộc khóa ngoại hiện có
ALTER TABLE TinhTP DROP CONSTRAINT fk_TinhTP_QuocGia;
ALTER TABLE QuanHuyen DROP CONSTRAINT fk_QuanHuyen_TinhTP;
ALTER TABLE PhuongXa DROP CONSTRAINT fk_PhuongXa_QuanHuyen;
ALTER TABLE KHACHHANG DROP CONSTRAINT fk_KhachHang_PhuongXa;
ALTER TABLE NHANVIEN DROP CONSTRAINT fk_NhanVien_PhuongXa;
ALTER TABLE NHACUNGCAP DROP CONSTRAINT fk_NhaCungCap_PhuongXa;

ALTER TABLE DONDATHANG DROP CONSTRAINT fk_DONDATHANG_KHACHHANG;
ALTER TABLE DONDATHANG DROP CONSTRAINT fk_DONDATHANG_NHANVIEN;
ALTER TABLE MATHANG DROP CONSTRAINT fk_MATHANG_NHACUNGCAP;
ALTER TABLE MATHANG DROP CONSTRAINT fk_MATHANG_LOAIHANG;
ALTER TABLE CHITIETDATHANG DROP CONSTRAINT fk_CHITIETDATHANG_DONDATHANG;
ALTER TABLE CHITIETDATHANG DROP CONSTRAINT fk_CHITIETDATHANG_MATHANG;

-- Thêm lại các ràng buộc khóa ngoại với ON UPDATE CASCADE và ON DELETE CASCADE
ALTER TABLE TinhTP
    ADD CONSTRAINT fk_TinhTP_QuocGia FOREIGN KEY (maQG) REFERENCES QuocGia(maQG) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE QuanHuyen
    ADD CONSTRAINT fk_QuanHuyen_TinhTP FOREIGN KEY (maTP) REFERENCES TinhTP(maTP) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PhuongXa
    ADD CONSTRAINT fk_PhuongXa_QuanHuyen FOREIGN KEY (maQH) REFERENCES QuanHuyen(maQH) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE KHACHHANG
    ADD CONSTRAINT fk_KhachHang_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE NHANVIEN
    ADD CONSTRAINT fk_NhanVien_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE NHACUNGCAP
    ADD CONSTRAINT fk_NhaCungCap_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DONDATHANG
    ADD CONSTRAINT fk_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DONDATHANG
    ADD CONSTRAINT fk_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN) ON UPDATE no action ON DELETE no action;

ALTER TABLE MATHANG
    ADD CONSTRAINT fk_MATHANG_NHACUNGCAP FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE MATHANG
    ADD CONSTRAINT fk_MATHANG_LOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CHITIETDATHANG
    ADD CONSTRAINT fk_CHITIETDATHANG_DONDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CHITIETDATHANG
    ADD CONSTRAINT fk_CHITIETDATHANG_MATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG) ON UPDATE no action  ON DELETE no action;
